sources:
  - QuixoticSeven-Light.ufo
  - QuixoticSeven-Regular.ufo
  - QuixoticSeven-Medium.ufo
  - QuixoticSeven-Semibold.ufo
  - QuixoticSeven-Bold.ufo
  - QuixoticFourteen-Regular.ufo
  - QuixoticSixteen-Regular.ufo
  - QuixoticSeven-LightItalic.ufo
  - QuixoticSeven-Italic.ufo
  - QuixoticSeven-MediumItalic.ufo
  - QuixoticSeven-SemiboldItalic.ufo
  - QuixoticSeven-BoldItalic.ufo
  - QuixoticFourteen-Italic.ufo
  - QuixoticSixteen-Italic.ufo
familyName: "Quixotic"
buildOTF: false
buildVariable: false