sources:
  - QuixoticSeven-Light.ufo
  - QuixoticSeven-Regular.ufo
  - QuixoticSeven-Medium.ufo
  - QuixoticSeven-Semibold.ufo
  - QuixoticSeven-Bold.ufo
  - QuixoticFourteen.ufo
  - QuixoticSixteen.ufo
  # - QuixoticSeven-LightOblique.ufo
  # - QuixoticSeven-Oblique.ufo
  # - QuixoticSeven-MediumOblique.ufo
  # - QuixoticSeven-SemiboldOblique.ufo
  # - QuixoticSeven-BoldOblique.ufo
  # - QuixoticFourteen-Oblique.ufo
  # - QuixoticSixteen-Oblique.ufo
familyName: "Quixotic"